feat: update deploy

diff --git a/.github/deploy/deploy-dongtai-server-test.yml b/.github/deploy/deploy-dongtai-server-test.yml
--- a/.github/deploy/deploy-dongtai-server-test.yml
+++ b/.github/deploy/deploy-dongtai-server-test.yml
@@ -1,4 +1,39 @@
 ---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: entrypoint
+  namespace: iast-test
+data:
+  config.ini: |-
+    #!/bin/bash
+    echo '启动uwsgi服务'
+    /bin/bash -c 'mkdir -p /tmp/{logstash/{batchagent,report/{img,word,pdf,excel,html}},iast_cache/package}'
+    python manage.py compilemessages  
+    sleep 2
+    python -c "import deploy.docker.version_update" || true
+    echo $1
+    
+    if [ "$1" = "worker" ]; then
+    	celery -A dongtai_conf worker -l info $DONGTAI_CONCURRENCY -E --pidfile= 
+    elif [ "$1" = "worker-beat" ]; then
+    	celery -A dongtai_conf worker -l info -Q dongtai-periodic-task $DONGTAI_CONCURRENCY -E --pidfile=
+    elif [ "$1" = "worker-high-freq" ]; then
+    	celery -A dongtai_conf worker -l info -Q dongtai-method-pool-scan,dongtai-replay-vul-scan $DONGTAI_CONCURRENCY -E --pidfile=
+    elif [ "$1" = "worker-es" ]; then
+    	celery -A dongtai_conf worker -l info -Q dongtai-es-save-task $DONGTAI_CONCURRENCY -E --pidfile=  
+    elif [ "$1" = "worker-sca" ]; then
+    	celery -A dongtai_conf worker -l info -Q dongtai-sca-task $DONGTAI_CONCURRENCY -E --pidfile=  
+    elif [ "$1" = "worker-other" ]; then
+    	celery -A dongtai_conf worker -l info -X dongtai-periodic-task,dongtai-method-pool-scan,dongtai-replay-vul-scan,dongtai-sca-task $DONGTAI_CONCURRENCY -E --pidfile= 
+    elif [ "$1" = "beat" ]; then
+    	celery -A dongtai_conf beat -l info $DONGTAI_CONCURRENCY  --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler
+    else
+    	# echo "Get the latest vulnerability rules." && python manage.py load_hook_strategy 2> /dev/null
+    	# if [ $? -ne 0 ]; then echo "ERROR: Lost connection to MySQL server !!!" && exit 1 ; else echo "succeed" ;fi
+    	uwsgi --ini /opt/dongtai/dongtai_conf/conf/uwsgi.ini $DONGTAI_CONCURRENCY
+    fi
+---
 # dongtai-server服务
 apiVersion: apps/v1
 kind: Deployment
@@ -31,6 +66,9 @@ spec:
             - name: configfile
               mountPath: /opt/dongtai/dongtai_conf/conf/config.ini
               subPath: config.ini
+            - name: entrypoint
+              mountPath: /opt/dongtai/deploy/docker/entrypoint.sh
+              subPath: entrypoint.sh
             - name: log-path
               mountPath: /tmp/logstash
           env:
@@ -47,6 +85,9 @@ spec:
         - name: configfile
           configMap:
             name: dongtai-iast-config.ini
+        - name: entrypoint
+          configMap:
+            name: entrypoint
         - name: log-path
           persistentVolumeClaim:
             claimName: app-agent-pvc
