Fix upgrade sql filter

diff --git a/deploy/docker-compose/dtctl b/deploy/docker-compose/dtctl
--- a/deploy/docker-compose/dtctl
+++ b/deploy/docker-compose/dtctl
@@ -1,5 +1,5 @@
 #!/bin/bash
-# set -e
+set -e
 set -o pipefail
 #echo "hello"
 _filename=$0
@@ -10,7 +10,7 @@ CHANGE_THIS_VERSION=""
 DOCKER_COMPOSE_FILE=""
 UPGRADE_DIR=~/dongtai_iast_upgrade
 DESTORY_DATA=false
-PROJECT_NAME=dongtai-iast
+PROJECT_NAME=dongtai
 
 Info() {
   echo -e "[Info] $1" >&2
@@ -32,7 +32,7 @@ Usage() {
   echo -e "\033[33m[Usage] $1 \033[0m" >&2
 }
 
-function print(){
+function print() {
   echo Print:$1 >&2
 }
 
@@ -91,10 +91,24 @@ function realpath() {
 shell_path=$(realpath "$0")
 shell_dir=$(dirname "$shell_path")
 
+# compare version
+function first_gt_second() {
+  first=${1//./}
+  second=${2//./}
+  if (($(echo "$first > $second" | bc -l))); then
+    echo true
+  else
+    echo false
+  fi
+}
 
-
-
+# get docker-compose project_name
+get_project_name() {
+  retval=$(docker-compose ls -q | grep dongtai)
+  echo "$retval"
+}
 function current_image_version() {
+  PROJECT_NAME=$(get_project_name)
   ver=$(docker ps | grep $PROJECT_NAME | grep "dongtai-webapi:" | awk '{split($2,a,":");print a[2]}')
   echo "$ver"
 }
@@ -105,6 +119,7 @@ function get_latest_release_version() {
 }
 
 function get_web_service_port() {
+  PROJECT_NAME=$(get_project_name)
   WEB_CONTAINER_ID=$(docker ps | grep $PROJECT_NAME | grep 'dongtai-web:' | awk '{print $1}')
   WEB_SERVICE_PORT=$(docker inspect --format='{{range $p, $conf := .NetworkSettings.Ports}} {{(index $conf 0).HostPort}} {{end}}' $WEB_CONTAINER_ID)
   WEB_SERVICE_PORT=$(trim $WEB_SERVICE_PORT)
@@ -116,7 +131,8 @@ function get_web_service_port() {
 # get mysql container id
 function get_mysql_container_id() {
   mysql_container_id=""
-  mysql_container_id=$(docker ps | grep "$PROJECT_NAME" | grep 'dongtai-mysql:' | awk '{print $1}')
+  PROJECT_NAME=$(get_project_name)
+  mysql_container_id=$(docker ps | grep "$PROJECT_NAME" | grep 'mysql' | awk '{print $1}')
   echo "$mysql_container_id"
 
 }
@@ -173,18 +189,15 @@ function restore_mysql() {
 
 }
 
+if [ ! -z "$(get_mysql_container_id)" ]; then
+  MOUNT_TYPE=$(docker inspect --format='{{range .Mounts}} {{.Type}} {{end}}' $(get_mysql_container_id))
+fi
+
+Info "Mount Type:$MOUNT_TYPE"
+
 # create docker compose file
 # Usage: create_docker_compose_file $VERSION $WEB_SERVICE_PORT $MYSQL_DATA_LOCATION
 function create_docker_compose_file() {
-
-
-  mysql_container_id=$(get_mysql_container_id)
-
-  if [ ! -z "$mysql_container_id" ]; then 
-    MOUNT_TYPE=$(docker inspect --format='{{range .Mounts}} {{.Type}} {{end}}' $(get_mysql_container_id))
-  fi
-
-  
 
   if [ ! -z "$1" ]; then
     CHANGE_THIS_VERSION=$1
@@ -199,18 +212,19 @@ function create_docker_compose_file() {
   else
     _DATA_DIR="mysql-vol"
   fi
-
+  Info $_DATA_DIR
   MYSQL_STR=""
   REDIS_STR=""
   if [ $SKIP_MYSQL == false ]; then
     export MYSQL_STR=$(
       cat <<EOF
 dongtai-mysql: 
-    #image: dongtai-mysql:1.1.2
+    # image: dongtai/dongtai-mysql:1.2.0.1
     image: dongtai/dongtai-mysql:$CHANGE_THIS_VERSION
     restart: always
     volumes:
       - "$_DATA_DIR:/var/lib/mysql:rw"
+      #- "/var/lib/mysql"
     logging:
       driver: "json-file"
       options:
@@ -432,7 +446,8 @@ if [ ! 0 == $# ]; then # If options provided then
     shift $((OPTIND - 1))
     op=$1
     shift
-    docker logs -f --tail=100 $(docker ps | grep $PROJECT_NAME | grep "dongtai-$op:" | awk '{print $1}') || exit 1
+    PROJECT_NAME=$(get_project_name)
+    docker logs -f --tail=200 $(docker ps | grep $PROJECT_NAME | grep "dongtai-$op:" | awk '{print $1}') || exit 1
     ;;
   "install") # install iast server
     #unset OPTIND
@@ -586,11 +601,15 @@ if [ ! 0 == $# ]; then # If options provided then
 
     docker_compose_file=$(create_docker_compose_file $(current_image_version) $(get_web_service_port))
 
+    PROJECT_NAME=$(get_project_name)
     if [ "$DESTORY_DATA" == true ]; then
       data_dir=$(get_database_data_dir)
       Notice "Data volume will be deleted."
       docker-compose -p $PROJECT_NAME -f <(echo "$docker_compose_file") down -v
-      # rm -rf $data_dir
+      if [ "$MOUNT_TYPE"=="bind" ]; then
+        Notice "Data will be deleted in $data_dir"
+        rm -rf $data_dir
+      fi
     else
       docker-compose -p $PROJECT_NAME -f <(echo "$docker_compose_file") down
     fi
@@ -632,13 +651,14 @@ if [ ! 0 == $# ]; then # If options provided then
 
     function execute_update() {
       # extract sql name and reverse list
-      SQL_NAMES=$(cat updaterecord.txt | awk "/$TO_VERSION/,/$FROM_VERSION/ {print \$2}" | grep -vF "$FROM_VERSION" | awk "{array[NR]=\$0} END { for(i=NR;i>0;i--) {print array[i];} }")
+
+      SQL_NAMES=$(cat updaterecord.txt | awk "/${TO_VERSION//./\\.}/,/${FROM_VERSION//./\\.}/ {print \$2}" | grep -vF "$FROM_VERSION" | awk "{array[NR]=\$0} END { for(i=NR;i>0;i--) {print array[i];} }")
 
       mysql_container_id=$(get_mysql_container_id)
       # check whether mysql is ready
       while :; do
         Info "start to check mysql status ..."
-        tables=$(docker exec -i $mysql_container_id /bin/bash -c "mysql -uroot -p'dongtai-iast'  --execute \"SHOW DATABASES;\"")
+        tables=$(docker exec -i $mysql_container_id /bin/bash -c "mysql -uroot -p'dongtai-iast'  --execute \"SHOW DATABASES;\"" || true)
         if [[ ${tables["mysql"]} ]]; then
           Notice "mysql instance ready!"
           break
@@ -646,10 +666,20 @@ if [ ! 0 == $# ]; then # If options provided then
         sleep 2
       done
 
+      # change sql store directory from /docker-entrypoint-initdb.d to /sql
+      # from 1.3.0
+      sql_dir="/docker-entrypoint-initdb.d"
+      if [[ $(first_gt_second $TO_VERSION 1.2.0) == true ]]; then
+        sql_dir="/sql"
+      fi
+
+      Info "Sql store directory: $sql_dir"
+
       # sql downloaded,start to execute sql
+      Info $SQL_NAMES
       for SQL in $SQL_NAMES; do
         Info "Start to load sql:[$SQL]"
-        docker exec -i $mysql_container_id /bin/bash -c "mysql -uroot -p'dongtai-iast' dongtai_webapi < /docker-entrypoint-initdb.d/$SQL"
+        docker exec -i $mysql_container_id /bin/bash -c "mysql -uroot -p'dongtai-iast' dongtai_webapi < $sql_dir/$SQL"
       done
 
     }
@@ -712,6 +742,7 @@ if [ ! 0 == $# ]; then # If options provided then
 
         "?")
           Error "Unknown option $OPTARG"
+          exit 1
           ;;
         esac
       done
@@ -722,9 +753,16 @@ if [ ! 0 == $# ]; then # If options provided then
       TO_VERSION=$(get_latest_release_version)
     fi
 
-    echo "FROM_VERSION:$FROM_VERSION,TO_VERSION:$TO_VERSION"
+    Info "Upgrade: $FROM_VERSION -> $TO_VERSION"
 
-    # backup_mysql
+    f_gt_t=$(first_gt_second $FROM_VERSION $TO_VERSION)
+
+    if [[ $f_gt_t == true ]]; then
+      Error "Your current verison is $FROM_VERSION, you can upgrade to later version. $TO_VERSION is invalid."
+      exit 1
+    fi
+
+    backup_mysql
     check_update_record_file
     check_schema_hash
     upgrade_docker_image
